### ISSUE TITLE
Logo in main menu slightly off

### ISSUE THREAD

**Issue by EvergreenTheTree** [alexdantas/nSnake#18]
### Screenshot:

![](https://mediacru.sh/V8LlGWJV72CK.png)

https://github.com/alexdantas/nSnake/blob/master/src/Display/Layouts/LayoutMainMenu.cpp#L94

For some reason, your string split function removes the space at the begining of the logo string.
It was really bothering me, so I though I'd bring it up.

**Comment by alexdantas** [comment]
That was a nice catch!
Its impressive how many times I saw that logo and did not realized it was slightly off...

Thanks, I just made some changes to fix that.
The `split` function does not automatically calls `trim` anymore; what was I thinking when I made that...?
