### ISSUE TITLE
Have levels with no walls with wrapping map

### ISSUE THREAD

**Issue by ghost** [alexdantas/nSnake#20]
I remember that in the original Snake game that there were levels on which there were no walls around the border of the map and that instead what would happen is that the snake would go through the border and come out of the other end of the map out of the opposite border.

I think that it would be really nice to have such maps/levels in this version of the Snake game.

**Comment by SeventhSonOfASeventhSon** [comment]
This bug has also been filed here downstream: https://bugs.launchpad.net/nsnake/+bug/1632861

**Comment by ghost** [comment]
Seems there is already such a feature! I just couldn't imagine it would be labelled as "Teleport" so that's why I didn't discover it earlier until someone pointed it out to me! Sorry for wasting your time with this report.
