### ISSUE TITLE
Man page error

### ISSUE THREAD

**Issue by cicku** [alexdantas/nSnake#4]
Hi,

when building the RPM the build tool returned:

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 1: warning: macro `"' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 5: warning: macro `"----------------------------------' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 9: warning: macro `"--------------------------------' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 17: warning: macro `"-------------------------------' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 44: warning: macro `"---------------------------------' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

nsnake.x86_64: W: manual-page-warning /usr/share/man/man6/nsnake.6.gz 63: warning: macro `"-----------------------------------' not defined
This man page may contain problems that can cause it not to be formatted as
intended.

So I think the man page's syntax may have some minor problem.

Will you be able to fix it?

Thanks.

**Comment by alexdantas** [comment]
Hi!
On my last commit I've attempted to fix that issue. Could you verify if things are ok?
If not, how could I get the same warning messages as you? Is there any tool that checks man pages?

Thanks for sending this issue!

**Comment by cicku** [comment]
I use rpmbuild to build the RPM, then it noted me about this...

Maybe you can release a new version?

Thanks.

**Comment by alexdantas** [comment]
Just released 1.7
Thanks for all the help!

**Comment by cicku** [comment]
Oh. Wrong nsnake version in manpage.

Please consider a fix later.

Thanks!

**Comment by alexdantas** [comment]
Wow, I should make a way to automatically refresh version and date on all docs.
Merged!
