### ISSUE TITLE
nsnake++: Error:   Exception: GameStateGame: Couldn't load the level.

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nSnake#6]
I started with single player, then `nsnake` exited with 255, the stderr.txt has the error as in issue summary.

There is no `levels/00.nsnake` in the `nsnake++` branch. Same thing for multiplay, just slightly different message and file.

I guess it's just forgetting to add the `levels` directory?

**Comment by livibetter** [comment]
It's fixed, thanks!

**Comment by alexdantas** [comment]
Thank you for pointing that out for me!
I forgot to add the level files.
