### ISSUE TITLE
Iniparser linker errors

### ISSUE THREAD

**Issue by dooks** [alexdantas/nSnake#7]
Commit 32af2bd3933bae03f2a86a97b41969703bfb5a0b breaks compilation involving iniparser.

> src/Config/INI.hpp:6:48: fatal error: iniparser/iniparser.h: No such file or directory
> # include <iniparser/iniparser.h> // local files
> 
> ```
>                                             ^
> ```
> 
> compilation terminated.
> make: [src/Flow/StateManager.o] Error 1

After changing it to #include<iniparser.h>, linker errors begin to pop up.

> Linking...
> src/Config/INI.o: In function INI::load(std::string):
> INI.cpp:(.text+0xbb): undefined reference to iniparser_load(char const_)
> src/Config/INI.o: In function INI::create():
> ...
> collect2: error: ld returned 1 exit status
> make: *_\* [nsnake] Error 1

Adding -liniparser to Makefile doesn't work. Probably needs an extern when including iniparser.h

**Comment by alexdantas** [comment]
Thanks, I didn't realized the urgency of this until now.

I feel bad for all the people who checked out the code
and gave up due to these errors... :(
